---
- name: Clean docker_target directory
  file:
    state: absent
    path: "{{ docker_target_dir }}/"
  ignore_errors: yes

- name: Create conf directory
  file: path={{ docker_target_dir }}/conf state=directory

- debug: msg={{ item }}
  with_fileglob: '{{ template_path }}/*.j2'

- name: Process template files
  template: src={{ item }} dest={{ docker_target_dir }}/conf/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob: '{{ template_path }}/*.j2'
